#!/bin/bash

source $(dirname $0)/docker
source $(dirname $0)/version

set -e

cd $(dirname $0)/..

mkdir -p dist/artifacts
cp bin/k3c dist/artifacts/k3c${SUFFIX}

IMAGE=${REPO}/k3c-data:${TAG}
DOCKERFILE=Dockerfile
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
fi

${DOCKER} build --target data -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}
