#!/bin/bash

set -e

REPO=${REPO:-rancher}
ARCH=${ARCH:-$(go env GOARCH)}
SUFFIX="-${ARCH}"

COMMIT=$(git rev-parse --short HEAD)
GIT_TAG=${DRONE_TAG:-$(git tag -l --contains HEAD | head -n 1)}
BUILD_DATE=$(date -u '+%Y-%m-%dT%H:%M:%SZ')

if [[ -n $(git status --porcelain --untracked-files=no) ]]; then
    DIRTY="-dirty"
fi

if [[ -z ${VERSION} ]]; then
    if [[ -z ${DIRTY} && -n ${GIT_TAG} ]]; then
        VERSION=${GIT_TAG}
    else
        VERSION=${COMMIT}${DIRTY}
    fi
fi

if [[ ${VERSION} == *dirty ]]; then
    TAG=dev
fi

TAG=${TAG:-${VERSION}${SUFFIX}}

VERSION_CONTAINERD=$(grep 'github.com/containerd/containerd' go.mod | head -n1 | awk '{print $4}')
if [ -z "$VERSION_CONTAINERD" ]; then
    VERSION_CONTAINERD="v0.0.0"
fi
